name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * * #8am ist
    - cron: 00 14 * * * #7:30pm ist
  
jobs:
  run-postmantests:
    runs-on: ec2-github-runner

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2
      
      - name: Install Node.js
        uses: actions/setup-node@v3.9.1
        with: 
          node-version: '22'

      - name: Install newman and htmml extra globally.
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the postman Collection with newman
        run: |
             newman run Newman_Inwarranty-flow_Collection_Final.postman_collection.json \
             -e QA.postman_environment.json \
             -d testData.csv \
             -r cli,htmlextra \
             --reporter-htmlextra-export ./newman/index.html

      - name: Newman Report
        if: always() #ensure this gets executed even if above step fails.
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: Newman Report
          path: newman/*.html
      - name: Creating git hub page branch
        if: always() #ensure this gets executed even if above step fails.
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smpt.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Test Execution Notification
          to: devanshshah.95@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
                Hi,
                Inwarranty flow has been executed and the report has been published and the URL is:https://devanshshah95.github.io/Phoenix_in_warranty_flow/

          

          
          
        
        
             
             
             
             
             
             
             
            
        

        
       
       
      
    
